### ISSUE TITLE
Presentation rules no longer apply, missing styling

### ISSUE THREAD

**Issue by armanhk** [yessenbayev/yessenbayev.github.io#4] opened 2020-07-30 17:33 UTC
Error in console: Uncaught TypeError: Cannot read property 'fn' of undefined -> bootstrap.min.js, line 6

See screenshot attached
![yessenbayev](https://user-images.githubusercontent.com/22483935/88954845-d8d04a80-d24f-11ea-87e2-d04d31d1fb46.PNG)

**Comment by yessenbayev** [comment] 2020-09-13 07:14
The issue is related to a corrupted cache with Bootstrap on the client-side. This can be fixed by refreshing the page or clearing browser data and then refreshing again.

Thank you))

**Closed as completed by yessenbayev** 2020-09-13 07:14 UTC
